from clint.textui import colored
import time
import os
def normal_banner():
    os.system("clear")
    print(colored.green("""███████████████▀▀██████████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""█████████████     ╙▀███████████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▀       ▓▀`▀▀███████████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████████▄,    ╓█▀      ║████████████████"""))
    time.sleep(0.3)
    print(colored.green("""█████████▀    ╙▀█▄▓█       ▓█▀█████████████"""))
    time.sleep(0.3)
    print(colored.green("""███████           "▀▀▄, ╓█▀    ╙███████████"""))
    time.sleep(0.3)
    print(colored.green("""█████▀               ╫▌▄█      ,▓╝█████████"""))
    time.sleep(0.3)
    print(colored.green("""███        ║█     ▄▄██▀      ▓█   ╙████████"""))
    time.sleep(0.3)
    print(colored.green("""█▀        4▓████▀` ▄▓      ▄█`    ,▄███████            --By:Aziz Kaplan--"""))
    time.sleep(0.3)
    print(colored.green("""█▄            "╣█▀▓██╗▄, ▄█`    ▄██████████               --Bruter19--"""))
    time.sleep(0.3)
    print(colored.green("""███▄            ╙█     `╙█▄  ,▄▀`██████████                 --V2.0--"""))
    time.sleep(0.1)
    print(colored.green("""█████▄           ╙▓▄      `▀▓▀   ██████████"""))
    time.sleep(0.1)
    print(colored.green("""███████▄           ▀▄           ║██████████"""))
    time.sleep(0.1)
    print(colored.green("""█████████           ╙█          ╣██████████"""))
    time.sleep(0.1)
    print(colored.green("""██████████▌          ▄█▄      ▄████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌        ╙▌     ╓██████████████"""))
    time.sleep(0.1)
    print(colored.green("""████████████▌               ███████████████"""))
    print(colored.green("""████████████                ║██████████████"""))
    print(colored.green("""███████████▌                ║██████████████"""))
    print(colored.green("""███████████                 ║██████████████"""))
    print(colored.green("""██████████▌▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄██████████████\n\n"""))
normal_banner()